### ISSUE TITLE
Edit project settings

### ISSUE THREAD

**Issue by likehopper** [ozguryazilimas/redmine_enforce_time_entry#4] opened 2021-11-26 13:01 UTC
I installed the plugin on a Redmine in version 4.2.3.
A non administrator can edit the project parameters,
but the validation of a change is prohibited.

**Comment by zaburt** [comment] 2021-11-29 16:31
Thank you for contacting us !

Does the user you are testing with, have permission to "log time" ? If the user is not allowed to "log time" we do not validate in the issue.

I have tried with Redmine 4.1.5 and 4.2.3, I do not see project settings as a regular user, even if I write the URL manually it does not work which is the intended behavior. Tried saving project settings, tried updating issues etc. all seem to work fine for me.

Are there other plugins installed in your environment ? It is possible other plugins may affect how this plugin works, can you try to disable other plugins (as in remove them from plugins folder in Redmine) and see if it makes a change ? If the issue still happens, can you provide steps to reproduce in detail ?

**Comment by likehopper** [comment] 2021-11-29 21:32
I'm login with a non admin user. This user has a role with all permissions for projects, issues and time tracking.

On fresh install with only Enforce Time Entry plugin, i do :
- Enable the module in the project settings : « http://xxx.xxx.xxx.xxx:3000/projects/test/settings/info ».
- Edit settings of plugin : http://xxx.xxx.xxx.xxx:3000/projects/test/settings/ete_project_settings
- Choose « Closed » and « Resolved » as « New Issue Status »
- I'm redirected to « http://xxx.xxx.xxx.xxx:3000/projects/test/ete_project_settings »
  and I get 403 error : « You are not authorized to access this page ».

For now, I configure each project as admin.

PJ : [enforce-time-entry-plugin.log](https://github.com/ozguryazilimas/redmine_enforce_time_entry/files/7621251/enforce-time-entry-plugin.log)

**Comment by zaburt** [comment] 2021-11-29 21:47
Thank you, I just made a change, it should be fixed now. Can you also try it ?

**Comment by likehopper** [comment] 2021-11-30 04:55
The 1.0.1 works for me! Good job!

**Comment by zaburt** [comment] 2021-11-30 07:57
Great ! Closing the issue then.

**Closed as completed by zaburt** 2021-11-30 07:57 UTC
